"""Vendored/generated triage tier — routing and audit-trail tests.

Routing contract (see core.audit.vendored_detector docstring):
corroborated generated files → SKIP; uncorroborated banners and all
structural/path evidence → GLANCE; boundary-adjacent functions never
skip; pinned gaps are untouched. Every skip/glance decision leaves a
suppressions.jsonl record and the run summary carries the counts.
"""

from __future__ import annotations

from core.audit.triage import (
    TriageBucket,
    classify_all,
    classify_function,
    vendor_decision,
)
from core.audit.vendored_detector import (
    KIND_GENERATED,
    KIND_VENDORED,
    VendorVerdict,
)


def _gap(file="wire.c", name="f", line_start=10, sloc=3, **kw):
    g = {
        "file": file,
        "name": name,
        "line_start": line_start,
        "line_end": line_start + sloc,
        "sloc": sloc,
        "kind": "function",
    }
    g.update(kw)
    return g


def _generated(corroborated=True):
    return VendorVerdict(
        kind=KIND_GENERATED,
        signal="banner",
        detail="generator banner: 'Generated by protoc'",
        corroborated=corroborated,
    )


def _vendored():
    return VendorVerdict(
        kind=KIND_VENDORED,
        signal="path",
        detail="vendored path segment 'third_party'",
    )


class TestClassifyFunctionRouting:
    def test_corroborated_generated_skips(self):
        tr = classify_function(
            file="gen/wire.c", function="f", sloc=3,
            vendor_verdict=_generated(corroborated=True),
        )
        assert tr.bucket == TriageBucket.SKIP
        assert vendor_decision(tr) == "skip"

    def test_uncorroborated_banner_glances_never_skips(self):
        # Anti-evasion: the banner is target-controlled text — alone
        # it never buys invisibility, only the cheap glance tier.
        tr = classify_function(
            file="mlkem768.h", function="f", sloc=3,
            vendor_verdict=_generated(corroborated=False),
        )
        assert tr.bucket == TriageBucket.GLANCE
        assert vendor_decision(tr) == "glance"

    def test_generated_entry_point_glances(self):
        tr = classify_function(
            file="gen/wire.c", function="f", sloc=3,
            is_entry_point=True,
            vendor_verdict=_generated(corroborated=True),
        )
        assert tr.bucket == TriageBucket.GLANCE
        assert vendor_decision(tr) == "glance"

    def test_generated_sink_glances(self):
        tr = classify_function(
            file="gen/wire.c", function="f", sloc=3,
            is_sink=True,
            vendor_verdict=_generated(corroborated=True),
        )
        assert tr.bucket == TriageBucket.GLANCE

    def test_vendored_glances(self):
        # A 100-SLOC vendored function would normally be INVESTIGATE.
        tr = classify_function(
            file="third_party/z.c", function="f", sloc=100,
            vendor_verdict=_vendored(),
        )
        assert tr.bucket == TriageBucket.GLANCE
        assert vendor_decision(tr) == "glance"

    def test_vendored_boundary_keeps_normal_routing(self):
        tr = classify_function(
            file="third_party/z.c", function="f", sloc=100,
            is_trust_boundary=True,
            vendor_verdict=_vendored(),
        )
        assert tr.bucket == TriageBucket.DEEP_DIVE
        assert vendor_decision(tr) is None

    def test_vendored_joern_flow_keeps_normal_routing(self):
        tr = classify_function(
            file="third_party/z.c", function="f", sloc=100,
            has_joern_flows=True,
            vendor_verdict=_vendored(),
        )
        assert tr.bucket == TriageBucket.DEEP_DIVE

    def test_no_verdict_normal_routing(self):
        tr = classify_function(file="a.c", function="f", sloc=100)
        assert tr.bucket == TriageBucket.INVESTIGATE
        assert vendor_decision(tr) is None

    def test_binary_absent_wins_over_vendor(self):
        # Oracle-earned dead-code skip stays the stronger verdict.
        tr = classify_function(
            file="gen/wire.c", function="f", sloc=3,
            binary_absent=True,
            vendor_verdict=_generated(corroborated=True),
        )
        assert tr.bucket == TriageBucket.SKIP
        assert any("binary_oracle_absent" in r for r in tr.reasons)
        assert vendor_decision(tr) is None


class TestClassifyAllGuards:
    def test_pinned_gap_exempt(self):
        gaps = [_gap(name="f", pinned=True), _gap(name="g", line_start=50, sloc=100)]
        results = classify_all(
            gaps,
            vendor_verdicts={"wire.c": _generated(corroborated=True)},
        )
        pinned = results["wire.c:f:10"]
        assert vendor_decision(pinned) is None
        assert pinned.bucket != TriageBucket.SKIP or not any(
            r.startswith("generated code") for r in pinned.reasons
        )
        # Unpinned sibling in the same file IS routed.
        assert vendor_decision(results["wire.c:g:50"]) == "skip"

    def test_force_review_gap_exempt(self):
        gaps = [_gap(name="f", force_review=True)]
        results = classify_all(
            gaps,
            vendor_verdicts={"wire.c": _generated(corroborated=True)},
        )
        assert vendor_decision(results["wire.c:f:10"]) is None

    def test_entry_point_key_glances(self):
        gaps = [_gap(name="f")]
        results = classify_all(
            gaps,
            entry_points=frozenset({"wire.c:f"}),
            vendor_verdicts={"wire.c": _generated(corroborated=True)},
        )
        assert results["wire.c:f:10"].bucket == TriageBucket.GLANCE

    def test_no_verdicts_no_change(self):
        gaps = [_gap(name="f", sloc=100)]
        results = classify_all(gaps, vendor_verdicts=None)
        assert results["wire.c:f:10"].bucket == TriageBucket.INVESTIGATE
